### ISSUE TITLE
Javascript filters to update Google Analytics

### ISSUE THREAD

**Issue by stuartlewis** [opentexts/opentexts#112]
Now that content is reloading via javascript (not a full page refresh), we need to capture Google Analystcs events each time the 'Futher results' or filters are canged.

[Example stackoverflow question/answer](https://stackoverflow.com/questions/9628547/google-analytics-how-to-track-pages-in-a-single-page-application)

```javascript
ga('send', 'pageview', '/some-page');
```

**Comment by brizee** [comment]
Is there anything else we'd like to catch in analytics whilst we're at it? I imagine tracking usages of various buttons might be interesting to build up a profile of how the site is used? Question for both you and @sarahmonster really :smile:

**Comment by sarahmonster** [comment]
These all sound like great metrics to track. I'd also include what people are searching for in there, but I don't think I've anything else to add right now.

We'll want to be sure we're respecting user privacy here—Google Analytics has some built-in privacy options, but they may need to be explicitly enabled. We'll also want to evaluate whether we need a cookie opt-in (probably yes) and create a privacy policy page so that people can manage their preferences (and understand how we're using the data).

**Comment by brizee** [comment]
Good points, I'd imagine in general we're interested in aggregate data rather than personal data here so can probably configure for maximum anonymity.

**Comment by stuartlewis** [comment]
Yes, let's add: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp

```javascript
ga('set', 'anonymizeIp', true);
```

**Comment by stuartlewis** [comment]
We also have query paramter tracking already enabled in Google Analytics:
![image](https://user-images.githubusercontent.com/135022/91969979-e4aba280-ed0e-11ea-8eb9-f2bfe22c0104.png)

**Comment by stuartlewis** [comment]
I'm guessing 'Dundee' is @brizee's default search term?! :)

![image](https://user-images.githubusercontent.com/135022/91970269-4e2bb100-ed0f-11ea-807a-eaefda2e4351.png)

**Comment by brizee** [comment]
Haha might just be 😄

**Comment by brizee** [comment]
Okay so, forgot Google Analytics was a bit awkward in how it tracks data, my thinking is the best set up would be to do the following:

### Custom Dimensions
* query - *The q value*
* libraryFilter - *The current selected library filter items as an alphabetised, comma separated list*
* languageFilter - *The current selected language filter items as an alphabetised, comma separated list*
* origin - *The library of origin for the active record, Hit scope only*

### Custom Metrics
* loadedTotal - *The total number of results the user has loaded*
* total - *The total number of results for this query*
* recordIndex - *The position of the record in the results, Hit scope only*

### Events
*Note: All given as [CATEGORY] -> [EVENT]*
* interaction -> outbound - *Triggered when a result is opened in any format, sets origin and recordIndex*
* interaction -> moreResults - *Triggered when the more results button is pressed*
* state -> allResultsLoaded - *Triggered when the more results button is hidden as all results are loaded*
* interaction -> export - *Triggered when the export all results button is pressed*
* interaction -> libraryFilterAdded - *Triggered when a new library filter value is ticked, value is passed as label, results after filter are passed as value*
* interaction -> libraryFilterRemoved - *Triggered when a library filter value is removed, value is passed as label*
* interaction -> languageFilterAdded - *Triggered when a new language filter value is ticked, value is passed as label, results after filter are passed as value*
* interaction -> languageFilterRemoved - *Triggered when a language filter value is removed, value is passed as label*

Since we're using Google Tag Manager it looks like I'd just pass the values in using relevant [events ](https://support.google.com/tagmanager/answer/6106716?hl=en&ref_topic=6333310) and [variables ](https://support.google.com/tagmanager/answer/6164990?hl=en) and let you hook them up as appropriate to analytics @stuartlewis?

**Comment by stuartlewis** [comment]
Thanks - sounds good.  Shall we start by implemeting a couple, check the data comes through, then do the rest?

**Comment by brizee** [comment]
Work ongoing for this in #152 next stage should be the Google Tag Manager dashboard pass I believe.
