### ISSUE TITLE
Performance tuning - suggestions

### ISSUE THREAD

**Issue by stuartlewis** [opentexts/opentexts#125]
An issue to discuss and share ideas for performance tuning. These are the easy ideas to get a bit of extra oomph before we move to load balanced servers / sharind solr across multiple servers. I've been playing with [loader.io](https://loader.io/) to get a bit of a benchmark, and currently a 2-processor/4GB RAM machine seems to reasonably reliably support 20 requests per second with a 2 second response time (therefore 40 concurrent connections). 

- [x] Don't retrieve fields from solr that aren't displayed (See: #124)
- [ ] Move static content (CSS / JS / IMGs) to a different server - won't do this for now, with caching + compression and the other scalability work, hopefully we won't need this.  Would be easy enough to do if we want to (put it behind CloudFront)
- [x] Give solr a bit more RAM (there's still a reasonable amount of non-allocated RAM on the machine
- [x] Add the web servers to a load balancer (design.opentexts.world)
- [x] Add the web servers to a load balancer (opentexts.world)
- [x] Enable compression (e.g. CSS now is now 10% of the size it was, so page loads in <0.5s rather than 1.1s)
- [x] Add caching to static objects

**Comment by brizee** [comment]
Just skimming this just now but do we know where the bottleneck lies? 

I made a demo GoLang app to replace the API portion of the PHP application a while ago and got response time down to 250ms from 1.25s - so it seems like most of the time might be in the HTTP Server/PHP but it'd be good to do a loadtest on the query in PHP vs the query directly against Solr maybe?

I'd definitely recommend moving static content to something more akin to a CDN with some aggressive caching.

Given the server app isn't stateful I'd maybe suggest from a resilience perspective it'd be better to investigate horizontal rather than vertical scaling - i.e. if it's cloud based anyway chuck a load balancer in front of it, then if we need too we can urgently spin up a new node and deploy onto that without having to wait for DNS propagation to get back online.

HTTP2 will only help clients that support it I imagine, so we can't factor it into baseline performance but still might not hurt.

Other than that yeah understanding if the bottleneck is Solr or HTTP will help us target any other actions, if it's Solr maybe more RAM helps - if it's HTTP then maybe we try and precalculate much more of the HTTP response (i.e. build the response once and save it to a temp file then reload that either pre-deployment or on first request)

**Comment by brizee** [comment]
Caveat all my advice by saying I've never been a full time DevOps - a lot of this is by osmosis, some by running servers for one game I developed whilst also developing them :smile:

**Comment by stuartlewis** [comment]
Thanks @brizee - I'll work on some these over the next week (e.g. have created [https://static.opentexts.org/](https://static.opentexts.org/) - right now just an alisas to the main site, but can move it elsewhere easily in the future - so will create a pull request to update the relevant URLs when running in a production environment CI_ENVIRONMENT).

To baseline performance I've got DataDog now monitoring the site, but of course this is under very little load right now.  So typical responses are about 0.5s, including connection / SSL handshake, etc.

![image](https://user-images.githubusercontent.com/135022/92582666-209fb400-f289-11ea-8292-09ea3ae41468.png)

We can also have a play with [https://codeigniter.com/userguide3/general/profiling.html](https://codeigniter.com/userguide3/general/profiling.html) which might be interesting, especially if we add extra timers around the solr query to see how much time is spent there versus the rest of the page processing.

**Comment by stuartlewis** [comment]
Interestingly: The very first protoype we built of this (about a year ago) was built using GoLang via [SolrDora](https://github.com/hectorcorrea/solrdora)!

**Comment by brizee** [comment]
Looks good, I think if peak is 20 requests/sec we could probably build a simple app to test this on local machines? Means we can simulate some demand more regularly (not sure what pricing is like for those cloud apps?) and get some end user timings. Since we're allowed through the firewall we could also simulate same demand just on Solr directly and diff them.

That Go app looks a bit more robust than mine right enough :) Was just hardcoding the connection details and then cleaning up the response and returning as json, more akin to our async endpoint.

**Comment by brizee** [comment]
Looked at this a bit more last night, from some testing on my own it seems that something causes the server to hang for about 5s periodically under load and generate a bunch of 500's but other than that it could probably handle a bit more (it builds up quite a backlog during those 5 seconds and then clears it pretty quickly). 

I'm still tidying up my test app to confirm beyond that but wonder if we could get some logs for those 500 errors? I wondered if it was maybe hitting a connection limit somehow but that doesn't seem to make sense either. The 500's don't reproduce in local environment unfortunately.

**Comment by stuartlewis** [comment]
I've seen similar - my guess is that it is a pause when Apache is spinning up its new threads. I've increased the idle thread count to 50 (was 5) which might help this.

Are the 500s from Apache/PHP, or from solr? If from Apache, this is probably because the default timeout for the solr connection is 5s, and that causes a 500 if a respinse is not received in enough time. I've addressed this in #133 which sets the timeout to 10s now (although opefully will rarely need that long).

I've also fixed a silly error: rather than editing firewall rules, development copies connect to solr via the solr.opentexts.world vhost in apache.  That's fine for development.  However I was also using this on the staging and production sites, which meant a loop-the-loop through apache, as the PHP app was conencting to solr via the solr.opentexts.world:80 proxy when it could just connect directly. This will now halve the number of apache threads required.

**Comment by brizee** [comment]
For the record @stuartlewis and myself continued this conversation in Slack - think we're in a much happier place with performance now and definitely satisfied that the main limitation is resources consumed by the PHP app so can be optimised in code.

**Comment by stuartlewis** [comment]
Compared to the [monitoring](https://github.com/opentexts/opentexts/issues/125#issuecomment-689452923) a week or two ago where we were averaging responses of about 0.5secs, the same test is now showing 0.2secs on average!

![image](https://user-images.githubusercontent.com/135022/94344002-0a794e00-0014-11eb-927e-6162b9ed611e.png)
