### ISSUE TITLE
Display filters in popover menus

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#13]
Instead of showing filters in a sidebar, where they can get a little long and hard to scroll, let's collapse them into expandable flyout/popover/dropdown/whatever menus, search engine style. This way, users who need to use the filters will have easy access to the relevant filters, but users who just want to get right into the results don't need to bother with them at all.

![language-filter](https://user-images.githubusercontent.com/376315/85640477-caf13d80-b683-11ea-81e9-a2d607ca9679.png)

Other notes:

- When/if we have more filter groups than the five shown here, we’ll want to hide the least useful ones under a “More…” mechanism. (See earlier mockups, but we can deal with this later as/when we add filters.)
- Can we make filters contextual, depending on the dataset returned? (Maybe as a v2)
- Would it help to show number of results for each filter, or does that just add extra noise?
- When a list of filters has more than 10 options, we should provide a search and attempt to show the most relevant or useful filters in a separate section at the top of the page (see #9)

**Comment by sarahmonster** [comment]
Filters with visual design applied:

<img width="232" alt="Screenshot 2020-08-10 at 13 27 39" src="https://user-images.githubusercontent.com/376315/89782479-45c7c800-db0d-11ea-8412-45ae8a0dc5df.png">

I've currently hidden the filters because they're a bit of a mess but we'll need to add them back. I can help with the visual design side of things but I'd love some help with the JS/functionality side of things!

**Comment by brizee** [comment]
Added a functional pass in `feature/filter-view`, doesn't completely match styles yet (though will look to @sarahmonster to finish the visual side)
![image](https://user-images.githubusercontent.com/188324/90049522-d3054b00-dccc-11ea-8931-cdf30f981df2.png)

I've gone for a slightly unconventional approach but it makes building the link much easier and keeps to minimal javascript.

**Comment by stuartlewis** [comment]
Hi Brian,

Many thanks for building this so quick - looks good.  I've swapped the test site (https://design.opentexts.world/) to your branch to see it in action.

Do you think it would be possible to tweak this further to allow mutiple facet values to be selected: e.g. Danish or French, rather than just a single facet value? (e.g. http://yonik.com/multi-select-faceting/).

And sorry for the question - it's just not a feature I've used before: what does the addTag and addExclude do which you've added in app/Controllers/Search.php?

Thanks again - much appreciated,


Stuart

**Comment by brizee** [comment]
Hey Stuart,

This should definitely be possible functionally - it might require some changes to the design from @sarahmonster though, my thoughts:

- The "All libraries/languages" button would have distinct interactions as it's the only one that would have to clear any other ticks, it might need to stand out visually
- Would we want to have select all/clear all style functionality to make it easier to get to the filter you want?
- Is it maybe preferable to move towards an "Apply" button for the filter? It would be quite frustrating to have to pick a language, wait for reload, pick a language until you get the selection you want.

It's possible given all this we'd rather make multi-facet filtering a separate issue and merge this in as a first pass?

And no worries about the question, the `addTag` and `excludeTag` are actually doing what's described in the first part ("1. User selects “Blue”) of http://yonik.com/multi-select-faceting/ - we tag the language filter and exclude it from the language facet - otherwise the counts calculated for that facet will be the counts with that filter applied (i.e. for any language other than the one you selected the count is 0 because you've filtered them all out). Just in case we decide to show the total results in the dropdown.

**Comment by brizee** [comment]
Oh and quick pass on Sarah's note:
> - When/if we have more filter groups than the five shown here, we’ll want to hide the least useful ones under a “More…” mechanism. (See earlier mockups, but we can deal with this later as/when we add filters.)

Make sense 😄 

> - Can we make filters contextual, depending on the dataset returned? (Maybe as a v2)

What we already had excluded filters with 0 results, that's def worth keeping - I think some of this merges with point 4 (and issue #9)?

> - Would it help to show number of results for each filter, or does that just add extra noise?

I had a look both with and without when mocking it here, what do you think about doing approximate numbers? Some results already are up to 2,000,000+ at which point the detail loses meaning - so maybe a (2M), (200k), (2k), (200), (2) style badge avoids it being too noisy whilst giving some context about what you can expect when you click on it?

> - When a list of filters has more than 10 options, we should provide a search and attempt to show the most relevant or useful filters in a separate section at the top of the page (see #9)

Sounds good, lets tackle under #9 - I'm imagining picking out most relevant by percentage of overall results included - say if something like 20% of results match this filter then it's a featured/useful/most relevant filter? but we can discuss under that issue 😁

**Comment by sarahmonster** [comment]
> The "All libraries/languages" button would have distinct interactions as it's the only one that would have to clear any other ticks, it might need to stand out visually

My suspicion is that we should be okay with styling that matches the other filters, but I can put this on my list of "things we can get a check on during testing". (Filters, generally speaking, would be super helpful to test, since there's lots going on with them.)

> Would we want to have select all/clear all style functionality to make it easier to get to the filter you want?

Select all: no! If there are cases where we think users would want to "select all", we're better off giving them a single option in the list ("All languages" or "Any time" for instance) and then clearing any other selected filters when the "All [x]" filter option is selected. This way, it becomes just another option in the list, with slightly adjusted behaviour (that matches users' expectations for how such an option would function).

Clear all: let's table this for now, and maybe consider it as an enhancement under #9 (or another follow-on issue) if needed. My first instinct here was "yes! I forgot that!" but then I looked more closely and, for most cases, the "All [x]" option again effectively acts as a "Clear all" function. I think it's possible that we'd need this in the future for specific filters, but I think we'd be best to evaluate the need on a case-by-case basis (and once we've had an opportunity to test the filters a bit more, since we'll be able to tell if it feels like a functionality that's missing.)

> Is it maybe preferable to move towards an "Apply" button for the filter? It would be quite frustrating to have to pick a language, wait for reload, pick a language until you get the selection you want.

So! The _ideal_ UX here is probably that selecting a filter would automatically filter the result set shown _without_ a page reload, so the result is more instantaneous. However, I realise that we may be limited here by the technical constraints of the current stack, so we may need to compromise, at least for a first iteration.

If the page needs to reload every time a filter is selected, I do think we'll need an apply button—you're right that the opposite would be a very poor experience. 

Here are some updated mockups, showing multiple selections at a time:

<img width="368" alt="Screenshot 2020-08-14 at 15 03 09" src="https://user-images.githubusercontent.com/376315/90257665-6068ac80-de3f-11ea-9791-7624c07038ef.png">
<img width="481" alt="Screenshot 2020-08-14 at 15 03 14" src="https://user-images.githubusercontent.com/376315/90257672-6199d980-de3f-11ea-8db3-e8dcdd3e1927.png">
<img width="407" alt="Screenshot 2020-08-14 at 15 03 21" src="https://user-images.githubusercontent.com/376315/90257677-62cb0680-de3f-11ea-9f68-8fff0ffc208b.png">
<img width="442" alt="Screenshot 2020-08-14 at 15 03 28" src="https://user-images.githubusercontent.com/376315/90257682-63639d00-de3f-11ea-8fe9-d939aa6a7c92.png">
<img width="356" alt="Screenshot 2020-08-14 at 15 03 37" src="https://user-images.githubusercontent.com/376315/90257685-63fc3380-de3f-11ea-9f92-8d5ecf624fd8.png">

Handling searching and other additional functionality as an add-on enhancement (ie, under #9 or a separate issue) sounds like a sensible approach to me. There's a lot of moving pieces with filters and I imagine it'll take a bit of back & forth to get them just right!

I'm a little uncertain myself about showing the number of results in the filters (it may introduce quite a lot of noise, and we want to be sure the signal:noise ratio is optimal) but that may be worth A/B testing to get a sense for how it might work once we have the basic filters built out. Sounds like it might be worth addressing as a follow-up issue once we have the core functionality worked out, and then we can try it to see if it adds value.

**Comment by stuartlewis** [comment]
Thanks - great discussions!  A few comments from me based on general library search system and facets:

 - I think numbers are helpful.  For example without them, I have no idea if I will get 2 results or 2million.  This also helps from an 'aerial view' type of approach.  I do a broad search, see the aerial view (e.g. how many results I will get by going down different routes) and then refine my search.  The facets can also help from a sereditptity point of view "Oh, I didn't realise you had ten thousand books in Arabic!".

 - Clear filter hopefully might be reasonably easy, as it just means dropping that query parameter altogether

 - Select all - as you say, this is the default option anyway, and is functionally the same as 'clear'.

Thanks! 

Stuart

**Comment by brizee** [comment]
All makes sense, I think Sarah's suggestion of looking over this when iterating makes the most sense but I guess to quickly clarify my concern with what we have just now there are two states that mean the exact same thing.

![image](https://user-images.githubusercontent.com/188324/90273400-cca2da80-de56-11ea-96c1-ab3a56d49315.png)
However the functionality available is very different between them - I think Library is the sort of awkward example where given the option to multi-filter you might be more likely to want to exclude one library than only include one, the steps for which are then to re-tick every library because it's in the first state. That's where the select all and clear all suggestions come from - if you want everything but one so we can keep an eye out for that. 

I agree with Stuart on the counts, I've not been interacting with the system much but I do find the ballpark count useful for knowing whether there might be something interesting under a particular filter. I've been doing a similar thing but for Latvian rather than Arabic as my partner is Latvian and it piqued my curiousity. :smile: but I do like a good A/B test.

**Comment by brizee** [comment]
Just pushed a new one on feature/filter-view - should add support for multiple filters. At this point happy to pass to @sarahmonster to make it stylish 😄
