### ISSUE TITLE
Tailwind cleanup

### ISSUE THREAD

**Issue by stuartlewis** [opentexts/opentexts#163]
From Slack...

https://tailwindcss.com/docs/controlling-file-size seems to be the ticket

**Comment by sarahmonster** [comment]
We should also:

- [opt into breaking changes early](https://tailwindcss.com/docs/upcoming-changes) (I can handle this since it'll require checking on compatibility, but I think we should be okay)
- [break the CSS file into smaller chunks](https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports) (I can handle the breaking it into logical chunks, but I had troubles getting the build system to actually import them)

I can probably get a PR started here, but I may need some help making everything work properly—build systems are not my area of strength!

**Comment by brizee** [comment]
I can probably provide builds support 😄

**Comment by stuartlewis** [comment]
This issue isn't quite so pressing now - I have enabled compression in Apache, and the CSS is now down to 140KB, rather than 1.4MB.
