### ISSUE TITLE
Inconsistent serialisation in CSV file

### ISSUE THREAD

**Issue by lb42** [opentexts/opentexts#194]
Searches for titles which include an apostrophe sometimes result in a quoted field in the corresponding CSV file, but sometimes don't. Why? Compare e.g. the downloaded results for "Ada Moore's story" (no quotes) and "Abbot's Cleve" (quotes). Some CSV-handling software requires the quotes.

**Comment by stuartlewis** [comment]
The CSV looks to be fully compliant with the [CSV specification](https://tools.ietf.org/html/rfc4180#section-2).  Quotes around values are only needed if they contain a comma or a new line, so that the CSV parser knows that the comma is not denoting a new field.  E.g. the following line has quotes not because of the apostrophes, bvut because of the comma in the title.

`Bodleian Libraries,"Carleton grange, by the author of 'Abbot's Cleve'."`

Then there are also titles that themselves contain quotes, which require a double quote:

`HathiTrust,"Carleton Grange : a novel / by the author of ""Abbot's Cleve."" 1"`

But an apostrophe is OK and does not require quotes:

`HathiTrust,Ada Moore's story : a novel.`

**Comment by lb42** [comment]
OK, I was misled by the fact that inserting quotes seemed to solve the problem. But clearly it's my manky old perl csv-handling software which is the problem here. Now that I can get the results in XML who cares!
