### ISSUE TITLE
Ensure filters are accessible to keyboard users

### ISSUE THREAD

**Issue by sarahmonster** [opentexts/opentexts#75]
Right now, the filters are impossible to use if you're using a keyboard only—we'll want these to be fully accessible to keyboard users, obviously! 

I'm attaching this to the Beta milestone since I do think it's pretty vital to the overall functionality of the site, but it's possible that none of our testers would be using keyboards to navigate the site, so if needed we can probably scoot this over to the "Polish" milestone if it's going to be hairy to sort out.

See #72 for further discussion.

**Comment by brizee** [comment]
Addressed in feature/javascript-filters - I decided to move away from the filter menu opening on focus and since I was doing some keybinds anyway give it some first rate support so:
* <kbd>Tab</kbd> onto filter button as normal
* Press <kbd>Space</kbd> or <kbd>Return</kbd> to open filter menu.
* Press <kbd>Tab</kbd> or <kbd>Down</kbd> to go to next entry, <kbd>Up</kbd> or <kbd>Shift</kbd> + <kbd>Tab</kbd> to go to previous entry.
* Press <kbd>Return</kbd> to activate entry.

**Comment by sarahmonster** [comment]
This sounds like a great approach! 👍 

It matches how this sort of behaviour would typically work on other sites, and I appreciate that there are a few different ways of navigating the filters, which makes the interaction more flexible & forgiving. 

Let me know when you have a PR ready for testing and I'm happy to try it out!

**Comment by brizee** [comment]
Feel free to hop in the branch whenever 😄 still a chunk to do but it's stable (at least for now)
